name: map-tree-genera-gpu

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - findutils
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - torchvision
  - pytorch-cuda=12.4
  - gdal
  - rasterio
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - fiona
  - pillow
  - tifffile
  - scikit-image
  - matplotlib-base
  - tqdm
  - requests
  - pyyaml
  - jupyterlab
  - ipykernel

  - pip:
      - opencv-python-headless
      - ultralytics==8.3.221
      - ultralytics-thop
      - albumentations
      - hydra-core
      - omegaconf
      - geojson
      - pycocotools
      - torchinfo
