name: map-tree-genera
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - numpy
  - pytorch::pytorch=2.2.0
  - torchvision=0.17.0
  - requests
  - seaborn
  - scikit-learn
  - scipy
  - setuptools
  - gdal
  - rasterio
  - shapely=2.0.1
  - pillow=9.4.0
  - pip:
      - albumentations==2.0.4
      - coolname==2.2.0
      - geojson==3.1.0
      - geopandas>=0.13.0
      - hydra-core==1.3.2
      - mit-semseg==1.0.0
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - OWSLib==0.32.1
      - pykrige==1.7.1
      - pytest
      - scikit_image==0.25.2
      - torch-summary==1.4.5
      - torchinfo==1.8.0
      - transformers==4.49.0
      - mercantile==1.2.1
      - ultralytics