name: map-tree-genera
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.4
  - pip
  # ---- numeric / ML ----
  - numpy=1.25.*
  - scipy>=1.16.*
  - scikit-learn=1.7.1
  - pandas=2.3.2
  # ---pytorch----
  - pytorch::pytorch=2.2.0
  - torchvision=0.17.0
  # ---- geospatial stack (ALL conda-forge) ----
  - gdal=3.7.2
  - rasterio=1.3.9
  - geopandas=1.1.1
  - shapely=2.0.1
  - pyproj=3.7.2
  - pyogrio=0.11.1
  - fiona=1.9.*
  - proj=9.3.0
  - geos=3.12.0
  # ---- imaging / IO ----
  - pillow=11.3.0
  - tifffile=2025.6.11
  - scikit-image=0.25.2
  - matplotlib-base=3.10.5
  - seaborn=0.13.2
  - tqdm=4.67.1
  - requests=2.32.5
  - pyyaml=6.0.2
  - opencv=4.9.*
  - pip:
      - albumentations==2.0.4
      - coolname==2.2.0
      - geojson==3.1.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - torch-summary==1.4.5
      - torchinfo==1.8.0
      - transformers==4.49.0
#      - mercantile==1.2.1
      - pycocotools
      - ultralytics==8.3.221
      - ultralytics-thop==2.0.17