name: map-tree-genera-gpu

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - findutils

  # core
  - numpy
  - scipy
  - pandas
  - scikit-learn

  # PyTorch GPU (driver CUDA 13 is fine; runtime can be CUDA 12.x)
  - pytorch
  - torchvision
  - pytorch-cuda=12.4

  # geospatial stack
  - gdal
  - rasterio
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - fiona

  # utils
  - pillow
  - tifffile
  - scikit-image
  - matplotlib-base
  - tqdm
  - requests
  - pyyaml

  - pip:
      - opencv-python-headless
      - ultralytics==8.3.221
      - ultralytics-thop
      - albumentations
      - hydra-core
      - omegaconf
      - geojson
      - pycocotools
      - torchinfo
