name: map-tree-genera

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip
  - findutils 
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - cpuonly
  - gdal
  - rasterio
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - fiona
  - pillow
  - tifffile
  - scikit-image
  - matplotlib-base
  - tqdm
  - requests
  - pyyaml
  - opencv
  - jupyterlab
  - ipykernel

  - pip:
      - ultralytics==8.3.221
      - ultralytics-thop
      - albumentations
      - hydra-core
      - omegaconf
      - geojson
      - pycocotools
      - torchinfo
